services:
  db:
    image: postgres    
    environment:
      - POSTGRES_DB=myawesomeblog
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5434:5432"
  web:
    build: .
    command: bash -c "
      python myawesomeblog/manage.py makemigrations blog events
      && sleep 15s
      && python myawesomeblog/manage.py migrate
      && python myawesomeblog/manage.py runserver 0.0.0.0:8000
      "
    ports:
      - "8010:8000"
    environment:
      - POSTGRES_NAME=myawesomeblog
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
