services:
  web:
    build: .
    command: python code/myawesomeblog/manage.py makemigrations blog events; python code/myawesomeblog/manage.py migrate
    volumes:
      - .:/code    
    environment:
      - POSTGRES_NAME=myawesomeblog
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
<<<<<<< HEAD
      - db
=======
      - db
>>>>>>> 642331d7d4560e85db6f2b02ef49468127613dd6
